# .rancher-pipelines --- rancher build pipeline definition
#
# Copyright (C) 2020 Kayisoft, Inc.
#
# Author: Mohammad Matini <mohammad.matini@outlook.com>
# Maintainer: Mohammad Matini <mohammad.matini@outlook.com>
#
# Description: Defines Rancher build pipeline for Kayishort.
#
# This file is part of Kayishort.
#
# Kayishort is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Kayishort is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Kayishort. If not, see <https://www.gnu.org/licenses/>.

stages:
- name: Build and Push Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: kayisoft/kayishort:${CICD_GIT_COMMIT}
      registry: 127.0.0.1:34776
timeout: 60
notification:
  recipients:
  - recipient: '#build-status'
    notifier: c-zjzqt:n-kppm5
  condition:
  - Success
  - Failed
